import hashlib
import base64
from starlette.requests import Request

def verify_password(plain_password: str, stored_hash: str) -> bool:
    """
    Verifies a password against a PBKDF2-SHA256 hash generated by our system.
    Format:
    $pbkdf2-sha256$<iterations>$<salt_b64>$<hash_b64>
    """
    try:
        _, algo, iterations, salt_b64, hash_b64 = stored_hash.split("$")

        if algo != "pbkdf2-sha256":
            return False

        salt = base64.b64decode(salt_b64)
        stored_key = base64.b64decode(hash_b64)

        derived_key = hashlib.pbkdf2_hmac(
            "sha256",
            plain_password.encode(),
            salt,
            int(iterations),
        )

        return derived_key == stored_key
    except Exception:
        return False


def is_admin_authenticated(request: Request) -> bool:
    return request.session.get("is_admin") is True
